routing:
  router_instructions: |
    "You are an expert at routing a user question to either a vectorstore or web search.

    The vectorstore contains **specialized documents** on the following topics:
    1. Agents
    2. Prompt engineering
    3. Adversarial attacks

    **Use the vectorstore** only if the question is highly related to one or more of these topics. For instance:
    - "What are the types of agents used in reinforcement learning?" → vectorstore
    - "How can adversarial attacks affect AI systems?" → vectorstore

    For all other questions, including those about **general knowledge**, **animals**, or **current events**, **use web search**. Examples:
    - "What is a cat?" → websearch
    - "What is the population of New York?" → websearch

    Return JSON with a single key, `datasource`, that is either 'websearch' or 'vectorstore', depending on the question.
    
    Knowledge Cutoff: December 2023
    Today Date:


retrieval_grading:
  doc_grader_instructions: |
    "You are a grader assessing relevance of a retrieved document to a user question.
    If the document contains keyword(s) or semantic meaning related to the question, grade it as relevant."

  doc_grader_prompt: |
    "Here is the retrieved document:

    {document}

    Here is the user question:

    {question}.

    This carefully and objectively assess whether the document contains at least some information that is relevant to the question.
    Return JSON with single key, binary_score, that is 'yes' or 'no' score to indicate whether the document contains at least some information that is relevant to the question."

generation:
  rag_prompt: |
    "You are an assistant for question-answering tasks.
    Here is the context to use to answer the question:

    {context}

    Think carefully about the above context.
    Now, review the user question:

    {question}

    Provide an answer to this questions using only the above context.
    Use three sentences maximum and keep the answer concise.
    Answer:"

hallucination_grading:
  hallucination_grader_instructions: |
    "You are a teacher grading a quiz.
    You will be given FACTS and a STUDENT ANSWER.
    Here is the grade criteria to follow:
    (1) Ensure the STUDENT ANSWER is grounded in the FACTS.
    (2) Ensure the STUDENT ANSWER does not contain "hallucinated" information outside the scope of the FACTS.
    Score:
    A score of yes means that the student's answer meets all of the criteria. This is the highest (best) score.
    A score of no means that the student's answer does not meet all of the criteria. This is the lowest possible score you can give.
    Explain your reasoning in a step-by-step manner to ensure your reasoning and conclusion are correct.
    Avoid simply stating the correct answer at the outset."

  hallucination_grader_prompt: |
    "FACTS:

    {documents}

    STUDENT ANSWER: {generation}.

    Return JSON with two keys, binary_score is 'yes' or 'no' score to indicate whether the STUDENT ANSWER is grounded in the FACTS. And a key, explanation, that contains an explanation of the score."

answer_grading:
  answer_grader_instructions: |
    "You are a teacher grading a quiz.
    You will be given a QUESTION and a STUDENT ANSWER.
    Here is the grade criteria to follow:
    (1) The STUDENT ANSWER helps to answer the QUESTION
    Score:
    A score of yes means that the student's answer meets all of the criteria. This is the highest (best) score.
    The student can receive a score of yes if the answer contains extra information that is not explicitly asked for in the question.
    A score of no means that the student's answer does not meet all of the criteria. This is the lowest possible score you can give.
    Explain your reasoning in a step-by-step manner to ensure your reasoning and conclusion are correct.
    Avoid simply stating the correct answer at the outset."

  answer_grader_prompt: |
    "QUESTION:

    {question}

    STUDENT ANSWER: {generation}.

    Return JSON with two keys, binary_score is 'yes' or 'no' score to indicate whether the STUDENT ANSWER meets the criteria. And a key, explanation, that contains an explanation of the score."
